### ISSUE TITLE
Some thing wrong in the Google RefExp dataset UMD spilt

### ISSUE THREAD

**Issue by lixyresearch** [varun-nagaraja/referring-expressions#2]
Sorry to disturb you.
The numbers in the paper are: 
the training partition contains 23199 images with 67996 objects and 85,408referring expressions.
The validation partition contains 2600 images with 7623 objects and 9,602 referring expressions.
# But the numbers we get from the released split is:
the training partition contains 23199 images with 44797 objects and 85,408referring expressions.
The validation partition contains 2600 images with 5023 objects and 9,602 referring expressions.
So, which one is right?

**Comment by varun-nagaraja** [comment]
You are right. Thanks for catching the typo. By mistake, I added the actual number of objects (44797) with the number of images (23199) and wrote that number. I will update the paper on arxiv.

**Comment by lixyresearch** [comment]
Thank you very much!
