### ISSUE TITLE
Broken URL Link

### ISSUE THREAD

**Issue by mees** [varun-nagaraja/referring-expressions#3]
I was following the readme but I can't download the Google RefExp and UNC RefExp splits with MCG candidates, somehow the link doesn't seem to work. Could you look into it please?
Broken url: https://obj.umiacs.umd.edu/referring-expressions/google_refexp_umd_split.tar.gz

**Comment by varun-nagaraja** [comment]
Sorry about that. I will try to upload that file at a new location and share the link here soon.

**Comment by varun-nagaraja** [comment]
The links should be back online now.
